# Generated by Django 2.2.5 on 2020-07-19 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=30)),
                ('billtoname', models.CharField(max_length=30)),
                ('adderss', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('billnum', models.CharField(max_length=30)),
                ('billdate', models.DateTimeField()),
                ('executvie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itemsdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('priceperqty', models.FloatField()),
                ('tax', models.FloatField()),
                ('discount', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust', to='billing.Customer')),
                ('products', models.ManyToManyField(to='products.Products')),
            ],
        ),
    ]
