# Generated by Django 2.2.5 on 2020-07-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20200718_1913'),
        ('products', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsdetails',
            name='priceperqty',
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='uom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.UOM'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='itemsdetails',
            name='products',
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
            preserve_default=False,
        ),
    ]
