# Generated by Django 2.2.5 on 2020-07-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20200720_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsstatus',
            name='billstatus_billnum',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='itm_billnum',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
