# Generated by Django 2.2.5 on 2020-07-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20200728_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billsstatus',
            name='paymentType',
        ),
    ]
