# Generated by Django 2.2.5 on 2020-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_role',
            field=models.CharField(default='', max_length=30),
        ),
    ]
