# Generated by Django 2.2.5 on 2020-07-31 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20200724_1249'),
        ('master', '0002_auto_20200718_1913'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.FloatField()),
                ('last_update_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invproducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('invuom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.UOM')),
            ],
        ),
        migrations.CreateModel(
            name='DamgedStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmgstock', models.FloatField()),
                ('dmg_last_update_date', models.DateTimeField()),
                ('dmgcreated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dmgproducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('dmguom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.UOM')),
            ],
        ),
    ]
