# Generated by Django 2.2.5 on 2020-07-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po',
            name='last_update_by',
        ),
    ]
