# Generated by Django 2.2.5 on 2020-07-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0002_remove_po_last_update_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poitems',
            name='priceperunit',
        ),
        migrations.RemoveField(
            model_name='poitems',
            name='total',
        ),
    ]
