# Generated by Django 2.2.5 on 2020-07-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0003_auto_20200730_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='potracker',
            name='po_num',
            field=models.CharField(default='100000000', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potracker',
            name='podetail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='po.Po'),
            preserve_default=False,
        ),
    ]
