# Generated by Django 2.2.5 on 2020-07-18 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('catagory', models.CharField(max_length=20)),
                ('Barcode', models.CharField(max_length=25)),
                ('mfgdate', models.DateField()),
                ('expdate', models.DateField()),
                ('price', models.FloatField()),
                ('status', models.BooleanField()),
                ('creationdate', models.DateTimeField()),
                ('last_update_date', models.DateTimeField()),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porductcreated', to=settings.AUTH_USER_MODEL)),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productupdated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
